# 项目配置信息
app:
  env: dev
  debug: false
  juhe_key: "xxxxxxx"
  admin_email:
    -
  public_key: |
    -----BEGIN PUBLIC KEY-----
    CiAdmin
    -----END PUBLIC KEY-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    ciAdmin
    -----END RSA PRIVATE KEY-----

server:
  http: 9503
  websocket: 9504
  tcp: 9505

# 日志配置
log:
  # 日志文件路径 *请使用绝对路径*
  path: "D:/Gim/go-chat/runtime"

# Redis 相关配置
redis:
  host: 192.168.163.145:6379
  auth: 20011224
  database: 10

# Mysql 数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  charset: utf8mb4
  username: root
  password: cxj2001
  database: gim_db
  collation: utf8mb4_general_ci

# Jwt 配置
jwt:
  secret: 836c3fea9bba4e04d51bd0fbcc5
  expires_time: 3600
  buffer_time: 3600

openai:
  key: "xxxx"
  proxy: "https://api.openai.com"

# 跨域配置
cors:
  origin: "*"
  headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
  methods: "OPTIONS,GET,POST,PUT,DELETE"
  credentials: false
  max_age: 600

# 文件系统配置【oss,qiniu 暂不支持】
filesystem:
  default: local
  local:
    # 文件保存的根目录
    root: "D:/Gim/GIM/"
    # 公开的 bucket
    bucket_public: "public"
    # 私有的 bucket
    bucket_private: "private"
    endpoint: "127.0.0.1"
    ssl: false
  minio:
    secret_id: "DW18OUT18YD5Q5WOKBXR"
    secret_key: "nVN2hIPjSmCJEgzQaYfJwz4IWRQmxdhRb2EJQ1"
    # 公开的 bucket
    bucket_public: "gim"
    # 私有的 bucket
    bucket_private: "gimprivate"
    endpoint: "http//192.168.163.154:9001"
    ssl: false

# 邮件配置
email:
  host: smtp.163.com
  port: 465
  username: xxxxx
  password: xxxxx
  fromname: "GIM 通讯系统"